# Site settings
title: "OM Sagita"
bye_message: "aselole"
baseurl: "https://omsagita.github.io"
url: "https://omsagita.github.io"
disqus: 

# Header settings
nick: "omsagita"
mail:
    domain: ""
    ext: ""
source_code:
    server: "github.com"
    nick: "omsagita"
blog:
    server: "github.io"
    nick: "omsagitq"
fingerprint_key: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
